name: Update OpenSky Flights

on:
  schedule:
    - cron: "*/30 * * * *"  # Every 30 minutes
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Run Python script
        run: python opensky_flights.py

      - name: Commit and push GeoJSON
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add opensky_flights.geojson
          git commit -m "Update GeoJSON with latest flight data" || echo "No changes to commit"
          git push
