name: Update OpenSky Flights

on:
  schedule:
    - cron: "*/30 * * * *"  # Every 30 minutes
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run script
        run: python opensky_flights.py

      - name: List files for debug
        run: ls -l

      - name: Commit and push GeoJSON
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git pull origin main --strategy=ours
          # Add files only if they exist
          if [ -f flight_points.json ]; then git add flight_points.json; fi
          if [ -f flight_trajectories.geojson ]; then git add flight_trajectories.geojson; fi
          git commit -m "Update flight data" || echo "No changes to commit"
          git push

